### PR TITLE
add request header for trace id

### PR DESCRIPTION
**Pull request by zffocussss**
- new request header **trace-id**

### CODE REVIEW

**Comment by matthyx** [comment]
Hi @zffocussss can you explain why you need a separate header for only trace-id? Is it for routing? As I understand the spec, opentracing clients should be capable of extracting it from the trace-parent header (which contains both trace-id and span-id), WDYT?

**Comment by zffocussss** [comment]
> WDYT

It is not mandatory, but it helps us add this info in logs when correlating apps tracing in some APM,such as elastic APM.
I am working on the kong logs, which logs can be modified by the request header.it is just a patch only.

**Comment by zffocussss** [comment]
I closed it,as it is not useful in common.

**Comment by matthyx** [comment]
> I closed it,as it is not useful in common.

Ok, as you wish. Thanks for your feedback, and if you really need it I don't mind merging :)

**Pull request closed without merging**
